# Generated by Django 6.0.1 on 2026-01-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='admin_avatars/'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='business_name',
            field=models.CharField(default='JJ Halal Farms', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
