# Generated by Django 6.0.1 on 2026-01-31 19:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pendinguser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendinguser',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='pendinguser',
            name='token',
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
