# Generated by Django 6.0.1 on 2026-02-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_phone_pendinguser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
